# The claims to be requested - this is used as the contents of the 'claims'
# parameter. 
claims:
  id_token:
    verified_claims:
      claims:
        given_name:
        family_name:
        birthdate:
      verification:
        trust_framework:
  userinfo:
    verified_claims:
      claims:
        given_name:
        family_name:
        birthdate:
      verification:
        trust_framework:

# Configure IDPs here.
idps:
  "yes Test-IDP":
    client_id: sandbox.yes.com:e85ff3bc-96f8-4ae7-b6b1-894d8dde9ebe
    cert_file: yes_sandbox_test_cert.pem
    key_file: yes_sandbox_test_key.pem
    redirect_uri: http://localhost:3000/yes/oidccb
    issuer_url: https://testidp.sandbox.yes.com/issuer/10000001
  "BankID":
    client_id: yes-daniel
    cert_file: /home/danielf/yes/my-keys/gain/bankid/cert.pem
    key_file: /home/danielf/yes/my-keys/gain/bankid/key.pem
    redirect_uri: http://localhost:3000/yes/oidccb
    issuer_url: https://gain.oidc.pki.nu
  "Dizme":
    client_id: 164610c7-faab-4d0e-a903-b111a2b45326
    client_secret: AVUNB7XnFU1elzuIomHs1yVVyzVSUbBW
    redirect_uri: http://localhost:3000/yes/oidccb
    issuer_url: https://gain-oidc-cl.dizme.io
    cert_file: None
    key_file: None
