claims:
  id_token:
    verified_claims:
      claims:
        given_name:
        family_name:
        birthdate:
      verification:
        trust_framework:

idps:
  "yes Test-IDP":
    client_id: sandbox.yes.com:e85ff3bc-96f8-4ae7-b6b1-894d8dde9ebe
    cert_file: yes_sandbox_test_cert.pem
    key_file: yes_sandbox_test_key.pem
    redirect_uri: http://localhost:3000/yes/oidccb
    issuer_url: https://testidp.sandbox.yes.com/issuer/10000001